CREATE TABLE IF NOT EXISTS garages_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name TEXT NOT NULL,
    product_price TEXT NOT NULL,
    date_posted TIMESTAMPTZ DEFAULT now() NOT NULL,
    userid INTEGER  REFERENCES garages_users(id) ON DELETE CASCADE NOT NULL,
    description TEXT NOT NULL
);